### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by birkenfeld** [jadpole/jadpole.github.io#14]
I enjoyed the series a lot! A few things I noticed while reading parts 1-11:
- `use` paths are always relative to the crate root. You can omit all leading `::` in them, which gets rid of some visual clutter.
- The section about the "old" EventPump with a lifetime threw me off, since I didn't read the disclaimer properly. Maybe add a comment to the code block itself `// note: does not compile anymore`?
- `thread::sleep_ms` is deprecated
- `ImmediateEvents` could get a `Default` derive, which gets rid of the `impl ImmediateEvents`
- I saw some comparison `x == true` which is unneeded.
- The Rectangle utility methods, as introduced in 1.6, don't compile.
- The initial code in 1.7, heading "Frames", does not compile (multiplying float*int).
- In 1.7, function `region()` (when explaining struct update syntax), the "rect would be made invalid" wouldn't matter since it's consumed by the function anyway.
- The "next" link from 1.10 leads to 1.10.
- In 1.11, using `mem::replace` and direct reassignment make the bullet update code much shorter:

```
        let old_bullets = mem::replace(&mut self.bullets, vec![]);
        self.bullets = old_bullets.into_iter().filter_map(|b| b.update(phi, elapsed)).collect();
```

**Comment by jadpole** [comment]
Thanks, I've fixed pretty much all of these. Committing ASAP.
