### ISSUE TITLE
Not specified where i have to add Asteroids code

### ISSUE THREAD

**Issue by jespino** [jadpole/jadpole.github.io#27]
Here: https://github.com/jadpole/jadpole.github.io/blame/master/_posts/2015-12-08-arcaders-1-10.md#L264 you change the context from define AnimatedSprite to define de Asteroids structure, I suppose the file to define it is views/game.rs but I'm not sure, and can be better to explicit specify the file.

**Comment by jadpole** [comment]
Thanks, fixed this in my next commit.
