### ISSUE TITLE
ArcadeRS:  no method named `load_texture` found for type `&sdl2::render::Renderer<'_>` in the current scope

### ISSUE THREAD

**Issue by crumblingstatue** [jadpole/jadpole.github.io#29]
This is caused by `sdl2_image` and our crate requiring different versions of `sdl2`. See https://github.com/xsleonard/rust-sdl2_image/issues/65.

One solution is not to allow a higher minor version than the one we specified, using `sdl2_image = "=1.0.0"`.

**Comment by Implox** [comment]
I've been running into the same problem as you. When I tried using that `sdl2_image = "=1.0.0"` dependency, everything compiled but I immediately ran into strange linking errors.

`error: linking with`cc`failed: exit code: 1`
`[huge blob omitted]`
`note: /usr/bin/ld: cannot find -lSDL2_ttf`

I'm not familiar enough with Rust to pin down the problem. What version of Rust are you compiling with?

**Comment by crumblingstatue** [comment]
That sounds like you don't have the native SDL2_ttf library properly installed on your system.

**Comment by Implox** [comment]
Gah, you're right. I don't know how I didn't catch that. Thanks!

**Comment by jadpole** [comment]
Yep. Also, "no method named `load_texture`" may occur if you're depending on a more recent version of rust-sdl2, which has changed a lot recently and I haven't quite kept the tutorials up to date.

**Comment by beeblebrox** [comment]
I am getting this issue. How do I sdl2 0.20 and sdl2_image together now that the 1.0.0 package isn't published?  There doesn't seem to be anything published past 0.19.0 on crate.io.

**Comment by malleusinferni** [comment]
The 1.x versions were unpublished as a result of confusion about semantic versioning rules (see #30) but development has not stopped.

If you inspect the release dates, you'll actually see that 0.19 is the most recent.
