### ISSUE TITLE
for 1.2(the 2nd step) - build error - There is no `EventPump` in `sdl2::event` [E0432]

### ISSUE THREAD

**Issue by ScottHuangZL** [jadpole/jadpole.github.io#4]
events.rs:1:5: 1:29 error: unresolved import `sdl2::event::EventPump`. There is no `EventPump` in `sdl2::event` [E0432]
events.rs:1 use ::sdl2::event::EventPump;
                ^~~~~~~~~~~~~~~~~~~~~~~~
events.rs:1:5: 1:29 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to previous error
Could not compile `arcade-rs`.

**Comment by k0pernicus** [comment]
Hello Scott!

The `EventPump` struct is located in the sdl2 package now.
So, you have to import `sdl2::EventPump` ;-)

**Comment by jadpole** [comment]
@k0pernicus You just saved me some minutes as well! :-)
